Fixes responsive SLC docs
google/horologist pull request #2007
Opened 2024-01-25 12:00 UTC by garanj

#### WHAT

Fixes responsive example for ScalingLazyColumn

#### WHY

Example doesn't build when copy/pasted

#### HOW

Fixed and confirmed build and execute

#### Checklist :clipboard:
- [N/A] Add explicit visibility modifier and explicit return types for public declarations
- [N/A] Run spotless check
- [N/A] Run tests
- [N/A] Update metalava's signature text files

2024-01-25 12:09 UTC, yschimke commented on docs/compose-layout.md
> +            Chip(
You need the import from compose-material

2024-01-25 12:10 UTC, yschimke requested changes
show an import?

2024-01-25 12:27 UTC, garanj commented on docs/compose-layout.md
> +            Chip(
Do you mean the original would work with an additional import? I have androidx.wear.compose:compose-material 1.3.0.

Maybe 

```
Chip(onClick = {}) {
    Text("Item $it")
}
```

is better?

2024-01-25 13:14 UTC, yschimke commented on docs/compose-layout.md
> +            Chip(
See https://google.github.io/horologist/compose-material/#compose-material

2024-01-25 15:18 UTC, garanj commented on docs/compose-layout.md
> +            Chip(
Got it!!

2024-01-25 15:20 UTC, garanj commented
Updated - apologies, makes sense now!😀

2024-01-25 15:23 UTC, yschimke commented on docs/compose-layout.md
> +import com.google.android.horologist.compose.material.Chip
TIOLI: should we import * here to not fix on specific classes. You are missing a lot of other imports.

2024-01-26 09:24 UTC, yschimke commented
Should we add a banner on top once showing imports come from compose-material?

2024-01-26 09:40 UTC, garanj commented
Added a note!

2024-01-26 10:24 UTC, merged