Tile preview and some improvements
google/horologist pull request #241
Opened 2022-06-16 16:19 UTC by yschimke

#### WHAT

Quick preview of material components for a Tile.

![image](https://user-images.githubusercontent.com/231923/174118201-6019f3e5-dab6-4a48-85d0-5d079f48e81c.png)

#### WHY

Want to validate colour choices when building tiles material screens.

#### HOW

Use a Tile with 5 material components and apply the theme.

#### Checklist :clipboard:
- [ ] Add explicit visibility modifier and explicit return types for public declarations
- [ ] Run spotless check
- [ ] Run tests
- [ ] Update metalava's signature text files

2022-06-16 16:20 UTC, yschimke commented
cc @ataulm

2022-06-17 10:16 UTC, ataulm requested changes
Just a change to the clickable name then LGTM

2022-06-17 10:16 UTC, ataulm commented on compose-tools/src/main/java/com/google/android/horologist/compose/tools/TilePreview.kt
> +public val DummyClickable: Clickable = Builder()
let's [change this one](https://developers.google.com/style/inclusive-documentation) to `NoOpClickable()`

2022-06-17 10:16 UTC, ataulm commented on sample/src/main/java/com/google/android/horologist/tile/SampleTheme.kt
> +public fun ThemePreview(theme: Colors) {
nit: Naming here is a little odd because this function isn't previewable. 

I guess we're not inlining it because we're showcasing how to pass a "theme", but how about renaming to `ThemeableTile` since this isn't a preview, the one above is?

2022-06-17 10:16 UTC, ataulm commented on tiles/src/main/java/com/google/android/horologist/tiles/preview/ThemePreviewTileRenderer.kt
> +    internal val DummyClickable: Clickable = Builder()
Do we need this or can we use the other one that's public in TilePreview? If we're keeping, let's rename.

2022-06-17 10:16 UTC, ataulm commented on tiles/src/main/java/com/google/android/horologist/tiles/render/RendererPreviewTileService.kt
> +    public abstract fun createResources(): R
Worth providing a default implementation (empty resources) here that can be overridden?

2022-06-17 10:41 UTC, yschimke commented on sample/src/main/java/com/google/android/horologist/tile/SampleTheme.kt
> +public fun ThemePreview(theme: Colors) {
Went with ThemePreviewTile

2022-06-17 10:42 UTC, yschimke commented on tiles/src/main/java/com/google/android/horologist/tiles/preview/ThemePreviewTileRenderer.kt
> +    internal val DummyClickable: Clickable = Builder()
I'll move NoOpClickable to the tiles module, but it's a dependency issue.

2022-06-17 11:05 UTC, yschimke commented on tiles/src/main/java/com/google/android/horologist/tiles/render/RendererPreviewTileService.kt
> +    public abstract fun createResources(): R
Maybe the name is wrong, you can't create an instance of R.  This is essentially mocking out the suspending work (producing images etc) before you build a Resources instance.

Changed to createResourcesInput() and added suspend.

2022-06-17 11:05 UTC, ataulm approved these changes

2022-06-17 11:56 UTC, merged