Accessibility changes for Pickers
google/horologist pull request #962
Opened 2023-01-30 11:08 UTC by rajat4064g

#### WHAT
Fixing accessibility in DatePicker and TimePicker.

#### WHY
Accessibility wasn't working properly in Pickers.

#### HOW
Handled Double Tap events appropriately to move from on picker to another and scrolling on the selected picker only irrespective of where it was performed on screen.

2023-01-30 14:31 UTC, BowerSteve requested changes

2023-01-30 14:31 UTC, BowerSteve commented on composables/src/main/java/com/google/android/horologist/composables/TimePicker.kt
> +                createDescription(focusedElement, hourState.selectedOption, "hours")
"hours", "minutes", "seconds" should come from string resources too, see content description strings below.

2023-01-30 14:31 UTC, BowerSteve commented on composables/src/main/java/com/google/android/horologist/composables/TimePicker.kt
> +}
Looks like these could be shared between DatePicker/TimePicker if made internal.

2023-01-31 06:17 UTC, rajat4064g commented on composables/src/main/java/com/google/android/horologist/composables/TimePicker.kt
> +}
`rememberTalkBackState` is made internal as that is required to be shared between files. These private methods are only needed here.

2023-01-31 08:50 UTC, rajat4064g commented on composables/src/main/java/com/google/android/horologist/composables/TimePicker.kt
> +                createDescription(focusedElement, hourState.selectedOption, "hours")
Done

2023-01-31 10:42 UTC, BowerSteve approved these changes

2023-01-31 10:51 UTC, yschimke commented on composables/src/main/java/com/google/android/horologist/composables/DatePicker.kt
> +    val datePickerState = remember(date) {
This makes sense.  But do we have API guidance on the general class of "Pickers" for how to respond to params changing.

Maybe not relevant in a wear app when used as full screen lifecycle.

But when implementing these pickers, is it clear that all state should be reset when the input changes?

cc @BowerSteve

2023-01-31 10:56 UTC, yschimke commented on composables/src/main/java/com/google/android/horologist/composables/DatePicker.kt
> +                    )[focusedElement.index].requestFocus()
Now that we have focus in Wear Foundation.

I think this should be using androidx.wear.compose.foundation.HierarchicalFocusCoordinator and friends.  If this Picker is in a Pager, it shouldn't request focus here.

2023-01-31 10:58 UTC, yschimke approved these changes
LGTM - one existing problem to resolve with focus, can be a follow up.

2023-01-31 11:49 UTC, merged